services:
  postgres:
    image: postgres:16-alpine
    container_name: isafae-e2e-postgres
    environment:
      POSTGRES_DB: isafae_test
      POSTGRES_USER: isafae_test_user
      POSTGRES_PASSWORD: test_password
    ports:
      - "5433:5432" # Use a different port to avoid conflict with dev db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U isafae_test_user" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - isafae-e2e-network

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    container_name: isafae-e2e-proxy
    ports:
      - "8001:8000" # Use a different port
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - isafae-e2e-network

networks:
  isafae-e2e-network:
    driver: bridge
